// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTecnicoWK.Data.Entity.MySQL.Contexto;

#nullable disable

namespace TesteTecnicoWK.Data.Entity.MySQL.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20220501020734__Inicio")]
    partial class _Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteTecnicoWK.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Dt_Alteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("Dt_Inclusao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("TesteTecnicoWK.Dominio.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("Dt_Alteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("Dt_Inclusao")
                        .HasColumnType("date");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Preco_Venda")
                        .HasPrecision(6, 2)
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("TesteTecnicoWK.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("TesteTecnicoWK.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TesteTecnicoWK.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
